-- begin CFD_EMPLOYEE
alter table CFD_EMPLOYEE add constraint FK_CFD_EMPLOYEE_ON_FIRE_DEPARTMENT foreign key (FIRE_DEPARTMENT_ID) references CFD_FIRE_DEPARTMENT(ID)^
alter table CFD_EMPLOYEE add constraint FK_CFD_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_CFD_EMPLOYEE_ON_FIRE_DEPARTMENT on CFD_EMPLOYEE (FIRE_DEPARTMENT_ID)^
create index IDX_CFD_EMPLOYEE_ON_USER on CFD_EMPLOYEE (USER_ID)^
-- end CFD_EMPLOYEE
-- begin CFD_OPERATION_REPORT
alter table CFD_OPERATION_REPORT add constraint FK_CFD_OPERATION_REPORT_ON_OPERATION foreign key (OPERATION_ID) references CFD_OPERATION(ID)^
alter table CFD_OPERATION_REPORT add constraint FK_CFD_OPERATION_REPORT_ON_CREATOR foreign key (CREATOR_ID) references CFD_EMPLOYEE(ID)^
create index IDX_CFD_OPERATION_REPORT_ON_OPERATION on CFD_OPERATION_REPORT (OPERATION_ID)^
create index IDX_CFD_OPERATION_REPORT_ON_CREATOR on CFD_OPERATION_REPORT (CREATOR_ID)^
-- end CFD_OPERATION_REPORT
-- begin CFD_COURSE_TOPIC_ATTACHMENT
alter table CFD_COURSE_TOPIC_ATTACHMENT add constraint FK_CFD_COURSE_TOPIC_ATTACHMENT_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table CFD_COURSE_TOPIC_ATTACHMENT add constraint FK_CFD_COURSE_TOPIC_ATTACHMENT_ON_COURSE_TOPIC foreign key (COURSE_TOPIC_ID) references CFD_COURSE_TOPIC(ID)^
create index IDX_CFD_COURSE_TOPIC_ATTACHMENT_ON_FILE on CFD_COURSE_TOPIC_ATTACHMENT (FILE_ID)^
create index IDX_CFD_COURSE_TOPIC_ATTACHMENT_ON_COURSE_TOPIC on CFD_COURSE_TOPIC_ATTACHMENT (COURSE_TOPIC_ID)^
-- end CFD_COURSE_TOPIC_ATTACHMENT
-- begin CFD_COURSE
alter table CFD_COURSE add constraint FK_CFD_COURSE_ON_COURSE_LEADER foreign key (COURSE_LEADER_ID) references CFD_EMPLOYEE(ID)^
alter table CFD_COURSE add constraint FK_CFD_COURSE_ON_TOPIC foreign key (TOPIC_ID) references CFD_COURSE_TOPIC(ID)^
create index IDX_CFD_COURSE_ON_COURSE_LEADER on CFD_COURSE (COURSE_LEADER_ID)^
create index IDX_CFD_COURSE_ON_TOPIC on CFD_COURSE (TOPIC_ID)^
-- end CFD_COURSE
-- begin CFD_EQUIPMENT
alter table CFD_EQUIPMENT add constraint FK_CFD_EQUIPMENT_ON_FIRE_DEPARTMENT foreign key (FIRE_DEPARTMENT_ID) references CFD_FIRE_DEPARTMENT(ID)^
create index IDX_CFD_EQUIPMENT_ON_FIRE_DEPARTMENT on CFD_EQUIPMENT (FIRE_DEPARTMENT_ID)^
-- end CFD_EQUIPMENT
-- begin CFD_OPERATION
alter table CFD_OPERATION add constraint FK_CFD_OPERATION_ON_RESPONSIBLE_DEPARTMENT foreign key (RESPONSIBLE_DEPARTMENT_ID) references CFD_FIRE_DEPARTMENT(ID)^
alter table CFD_OPERATION add constraint FK_CFD_OPERATION_ON_OPERATION_LEAD foreign key (OPERATION_LEAD_ID) references CFD_EMPLOYEE(ID)^
alter table CFD_OPERATION add constraint FK_CFD_OPERATION_ON_TYPE foreign key (TYPE_ID) references CFD_OPERATION_TYPE(ID)^
create index IDX_CFD_OPERATION_ON_RESPONSIBLE_DEPARTMENT on CFD_OPERATION (RESPONSIBLE_DEPARTMENT_ID)^
create index IDX_CFD_OPERATION_ON_OPERATION_LEAD on CFD_OPERATION (OPERATION_LEAD_ID)^
create index IDX_CFD_OPERATION_ON_TYPE on CFD_OPERATION (TYPE_ID)^
-- end CFD_OPERATION
-- begin CFD_MAINTENANCE
alter table CFD_MAINTENANCE add constraint FK_CFD_MAINTENANCE_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references CFD_EQUIPMENT(ID)^
alter table CFD_MAINTENANCE add constraint FK_CFD_MAINTENANCE_ON_PERFORMED_BY foreign key (PERFORMED_BY_ID) references CFD_EMPLOYEE(ID)^
create index IDX_CFD_MAINTENANCE_ON_EQUIPMENT on CFD_MAINTENANCE (EQUIPMENT_ID)^
create index IDX_CFD_MAINTENANCE_ON_PERFORMED_BY on CFD_MAINTENANCE (PERFORMED_BY_ID)^
-- end CFD_MAINTENANCE
-- begin CFD_COURSE_EMPLOYEE_LINK
alter table CFD_COURSE_EMPLOYEE_LINK add constraint FK_COUEMP_ON_COURSE foreign key (COURSE_ID) references CFD_COURSE(ID)^
alter table CFD_COURSE_EMPLOYEE_LINK add constraint FK_COUEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references CFD_EMPLOYEE(ID)^
-- end CFD_COURSE_EMPLOYEE_LINK
-- begin CFD_FIRE_DEPARTMENT
alter table CFD_FIRE_DEPARTMENT add constraint FK_CFD_FIRE_DEPARTMENT_ON_FIRE_CHIEF foreign key (FIRE_CHIEF_ID) references CFD_EMPLOYEE(ID)^
create index IDX_CFD_FIRE_DEPARTMENT_ON_FIRE_CHIEF on CFD_FIRE_DEPARTMENT (FIRE_CHIEF_ID)^
-- end CFD_FIRE_DEPARTMENT
