alter table CFD_OPERATION_REPORT add constraint FK_CFD_OPERATION_REPORT_ON_OPERATION foreign key (OPERATION_ID) references CFD_OPERATION(ID);
alter table CFD_OPERATION_REPORT add constraint FK_CFD_OPERATION_REPORT_ON_CREATOR foreign key (CREATOR_ID) references CFD_EMPLOYEE(ID);
create index IDX_CFD_OPERATION_REPORT_ON_OPERATION on CFD_OPERATION_REPORT (OPERATION_ID);
create index IDX_CFD_OPERATION_REPORT_ON_CREATOR on CFD_OPERATION_REPORT (CREATOR_ID);
