alter table CFD_EQUIPMENT add constraint FK_CFD_EQUIPMENT_ON_FIRE_DEPARTMENT foreign key (FIRE_DEPARTMENT_ID) references CFD_FIRE_DEPARTMENT(ID);
create index IDX_CFD_EQUIPMENT_ON_FIRE_DEPARTMENT on CFD_EQUIPMENT (FIRE_DEPARTMENT_ID);
