alter table CFD_OPERATION add constraint FK_CFD_OPERATION_ON_RESPONSIBLE_DEPARTMENT foreign key (RESPONSIBLE_DEPARTMENT_ID) references CFD_FIRE_DEPARTMENT(ID);
alter table CFD_OPERATION add constraint FK_CFD_OPERATION_ON_OPERATION_LEAD foreign key (OPERATION_LEAD_ID) references CFD_EMPLOYEE(ID);
alter table CFD_OPERATION add constraint FK_CFD_OPERATION_ON_TYPE foreign key (TYPE_ID) references CFD_OPERATION_TYPE(ID);
create index IDX_CFD_OPERATION_ON_RESPONSIBLE_DEPARTMENT on CFD_OPERATION (RESPONSIBLE_DEPARTMENT_ID);
create index IDX_CFD_OPERATION_ON_OPERATION_LEAD on CFD_OPERATION (OPERATION_LEAD_ID);
create index IDX_CFD_OPERATION_ON_TYPE on CFD_OPERATION (TYPE_ID);
