alter table CFD_EMPLOYEE add constraint FK_CFD_EMPLOYEE_ON_FIRE_DEPARTMENT foreign key (FIRE_DEPARTMENT_ID) references CFD_FIRE_DEPARTMENT(ID);
create index IDX_CFD_EMPLOYEE_ON_FIRE_DEPARTMENT on CFD_EMPLOYEE (FIRE_DEPARTMENT_ID);
