alter table CFD_MAINTENANCE add constraint FK_CFD_MAINTENANCE_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references CFD_EQUIPMENT(ID);
alter table CFD_MAINTENANCE add constraint FK_CFD_MAINTENANCE_ON_PERFORMED_BY foreign key (PERFORMED_BY_ID) references CFD_EMPLOYEE(ID);
create index IDX_CFD_MAINTENANCE_ON_EQUIPMENT on CFD_MAINTENANCE (EQUIPMENT_ID);
create index IDX_CFD_MAINTENANCE_ON_PERFORMED_BY on CFD_MAINTENANCE (PERFORMED_BY_ID);
