alter table CFD_EQUIPMENT add constraint FK_CFD_EQUIPMENT_ON_OPERATIONAL_MANUAL foreign key (OPERATIONAL_MANUAL_ID) references SYS_FILE(ID);
create index IDX_CFD_EQUIPMENT_ON_OPERATIONAL_MANUAL on CFD_EQUIPMENT (OPERATIONAL_MANUAL_ID);
